@IsTest
private class ClassForAdditinalCoverageTest {
    static testMethod void testBehavior() {
        ClassForAdditinalCoverage someClass = new ClassForAdditinalCoverage();
        someClass.coverage1();
        someClass.coverage2();
        someClass.coverage3();
        someClass.coverage4();
        someClass.coverage5();
        someClass.coverage6();
        someClass.coverage7();
        someClass.coverage8();
        someClass.coverage9();
        someClass.coverage10();
    }
}