@isTest
private class TestSharingConfigurator {
/*	static testMethod void mySharingConfiguratorTest() {
		testDataSetupUtil_v2.setUPCoreData(2);
        testDataSetupUtil_v2.setUPStaffData(2);
        testDataSetupUtil_v2.setUPStudentData(2);
        
        
        test.startTest();
        SharingConfigurator sc = new SharingConfigurator();
        Database.executeBatch(sc);
		test.stoptest();        
        
	}
*/
}