*REQ*Name,*REQ*Behavior Category/Categories,Incident Level,Corresponding Value,incident involves weapon?
T3 - Hazing,Bullying / Threatening / Planning Harm,Negative,3,FALSE
T5 - Planned assault/physical attack on student or staff where there is or has t,Bullying / Threatening / Planning Harm,Negative,5,FALSE
T5 - Using an article that is not normally considered a weapon to intimidate or,Bullying / Threatening / Planning Harm;Fighting;Having / Using Potential or Real Weapon,Negative,5,TRUE
T1 - Behaviors that disrupt or interfere with classroom teaching and learning,Disruptive / Disrespectful,Negative,1,FALSE
T4 - Interfering with school authorities or participating in a major disruption,Disruptive / Disrespectful,Negative,4,FALSE
T1 - Communication or tone and language that is not respectful (including teasin,Disruptive / Disrespectful,Negative,1,FALSE
T2 - Directing profanity or offensive gestures toward others,Disruptive / Disrespectful,Negative,2,FALSE
T4 - Sexual harassment,Disruptive / Disrespectful,Negative,4,FALSE
T1 - Any (Tier 1) behavior or other conduct not specifically enumerated in any o,Disruptive / Disrespectful,Negative,1,FALSE
T5 - Possession of drug paraphernalia or controlled substance,Drugs / Alcohol,Negative,5,FALSE
T5 - Possession or distribution of alcohol,Drugs / Alcohol,Negative,5,FALSE
T5 - Possession of a weapon,Having / Using Potential or Real Weapon,Negative,5,TRUE
T5 - Using an article that is not normally considered a weapon to injure another,Having / Using Potential or Real Weapon,Negative,5,TRUE
T4 - Possession of tools or instruments which school administrators deem could b,Having / Using Potential or Real Weapon,Negative,4,TRUE
T5 - Commission or attempted commission of any act of sexual assault or sexual a,Inappropriate Contact / Unsafe Behavior,Negative,5,FALSE
T1 - Inappropriate displays of affection,Inappropriate Contact / Unsafe Behavior,Negative,1,FALSE
T2 - Inappropriate physical contact between students that may not be physically,Inappropriate Contact / Unsafe Behavior,Negative,2,FALSE
T5 - Possession of fireworks or explosives,Inappropriate Contact / Unsafe Behavior;Having / Using Potential or Real Weapon,Negative,5,TRUE
T2 - Lying with intent to mislead,Lying / Cheating / Stealing,Negative,2,FALSE
T3 - Academic Dishonesty,Lying / Cheating / Stealing,Negative,3,FALSE
T3 - Forgery,Lying / Cheating / Stealing,Negative,3,FALSE
T4 - Tampering with or altering an official school record or document,Lying / Cheating / Stealing,Negative,4,FALSE
T3 - Impulsive theft that does not involve going into personal belongings (takin,Lying / Cheating / Stealing,Negative,3,FALSE
T4 - Planned theft that involves going into personal belonging or space,Lying / Cheating / Stealing,Negative,4,FALSE
T2 - Unauthorized use of portable electronic devices during school hours,Misusing Materials / Damaging Property,Negative,2,FALSE
T2 - Intentional misuse of school equipment/supplies/facilities,Misusing Materials / Damaging Property,Negative,2,FALSE
T3 - Throwing objects that may cause injury or damage property,Misusing Materials / Damaging Property,Negative,3,FALSE
T4 - Intentional vandalism or destruction of property under $500,Misusing Materials / Damaging Property,Negative,4,FALSE
T4 - Intentional vandalism or destruction of property over $500,Misusing Materials / Damaging Property,Negative,4,FALSE
T2 - Using computer/office equipment without permission,Misusing Materials / Damaging Property;Inappropriate Contact / Unsafe Behavior,Negative,2,FALSE
Neutral Incident #2,Neutral #1;Neutral #2,Neutral,1,FALSE
Neutral Incident #1,Neutral #1;Neutral #2,Neutral,3,FALSE
T1 - Noncompliance with an approved dress code,Non-compliant / Not Prepared,Negative,-1,FALSE
T1 - Attending class without required class materials or assigned work,Non-compliant / Not Prepared,Negative,1,FALSE
T1 - Off-task behaviors that demonstrate disengagement from classroom learning,Non-compliant / Not Prepared,Negative,1,FALSE
T2 - Unexcused absence from class,Not In Class or With Group / Truancy,Negative,2,FALSE
T2 - Unexcused absence from school,Not In Class or With Group / Truancy,Negative,2,FALSE
T1 - Unexcused tardiness for class or school,Not In Class or With Group / Truancy,Negative,1,FALSE
T2 - Unauthorized presence in hallway during class time,Not In Class or With Group / Truancy,Negative,2,FALSE
T2 - Leaving classroom or group without permission,Not In Class or With Group / Truancy,Negative,2,FALSE
T3 - Engaging in behavior that demonstrates gang/neighborhood crew affiliation (,Other,Negative,3,FALSE
T4 - Retaliation for reporting harassment and sexual harassment,Other,Negative,4,FALSE
T1 - Any behavior not specifically enumerated in any other tier that is disrespe,Other,Negative,1,FALSE
T2 - Any behavior not specifically enumerated in any other tier that causes disr,Other,Negative,2,FALSE
T3 - Any behavior not specifically enumerated in any other tier that causes sign,Other,Negative,3,FALSE
T4 - Any behavior not specifically enumerated in any other tier that causes disr,Other,Negative,4,FALSE
T2 - Documented pattern of persistent Tier 1 behavior,Other,Negative,2,FALSE
T3 - Documented pattern of persistent Tier 2 behavior,Other,Negative,3,FALSE
T4 - Documented pattern of persistent Tier 3 behavior,Other,Negative,4,FALSE
T5 - Documented pattern of persistent Tier 4 behavior,Other,Negative,5,FALSE
T3 - Gambling,Other,Negative,3,FALSE
Positive Incident #1,Positive #1,Positive,1,FALSE
Positive Incident #2,Positive #1;Positive #2,Positive,1,FALSE
