Present,Attendance,P,sf_present,Present,1,TRUE,Present,,,,FALSE,,FALSE,
Tardy,Attendance,UT,sf_tardy,Tardy,2,FALSE,Tardy,,,,FALSE,,FALSE,
Excused Tardy,Attendance,ET,sf_tardy,Excused Tardy,3,FALSE,Excused Tardy,,,,FALSE,,FALSE,
Unexcused Absence,Attendance,UA,sf_absent,Unexcused Absence,4,FALSE,Unexcused Absence,,,,FALSE,,FALSE,
Excused Absence,Attendance,EA,sf_absent,Excused Absence,5,FALSE,Excused Absence,,,,FALSE,,FALSE,
Early Departure,Attendance,UD,sf_departed,Early Departure,6,FALSE,Early Departure,,,,FALSE,,FALSE,
Tardy/Early Departure,Attendance,TED,sf_tardy,Tardy and Early Departure,7,FALSE,Tardy Departure,,,,FALSE,,FALSE,
Excused Early Departure,Attendance,ED,sf_departed,Excused Early Departure,8,FALSE,Excused Early Departure,,,,FALSE,,FALSE,
In-school Suspension,Attendance,IS,sf_suspended,In-school Suspension,9,FALSE,In-school Suspension,,,,FALSE,,FALSE,
Out of school Suspension,Attendance,OS,sf_suspended,Out of school Suspension,10,FALSE,Out of school Suspension,,,,FALSE,,FALSE,
Awaiting Admin Decision,Behavior_Consequence,,,,1,FALSE,,,,0,FALSE,,FALSE,
Buddy Classroom/Reflection Room,Behavior_Consequence,,,,2,FALSE,,,,15,FALSE,,FALSE,
Conference with Administrator,Behavior_Consequence,,,,3,FALSE,,,,20,FALSE,,FALSE,
Conference with BCC,Behavior_Consequence,,,,4,FALSE,,,,10,FALSE,,FALSE,
Fieldwork Restriction,Behavior_Consequence,,,,5,FALSE,,,,0,FALSE,,FALSE,
Lose Free Time (Recess),Behavior_Consequence,,,,7,FALSE,,,,20,FALSE,,FALSE,
Other,Behavior_Consequence,,,,8,FALSE,,,,0,FALSE,,FALSE,
Other Loss of Privilege,Behavior_Consequence,,,,9,FALSE,,,,0,FALSE,,FALSE,
Other Time Away,Behavior_Consequence,,,,10,FALSE,,,,0,FALSE,,FALSE,
Refocus Center (Time after school),Behavior_Consequence,,,,11,FALSE,,,,0,FALSE,,FALSE,
Saturday Detention,Behavior_Consequence,,,,12,FALSE,,,,180,FALSE,,FALSE,
Service (Break It Fix it),Behavior_Consequence,,,,13,FALSE,,,,0,FALSE,,FALSE,
Silent Lunch,Behavior_Consequence,,,,14,FALSE,,,,20,FALSE,,FALSE,
Student Sent Home (Not Suspended),Behavior_Consequence,,,,15,FALSE,,,,0,FALSE,,FALSE,
Suspendable (Waived),Behavior_Consequence,,,,16,FALSE,,,,0,FALSE,,FALSE,
Suspension (In School),Behavior_Consequence,,sf_suspension,,17,FALSE,,,,420,FALSE,,FALSE,
Suspension (Out of School),Behavior_Consequence,,sf_suspension,,18,FALSE,,,,420,FALSE,,FALSE,
Missing,Homework,,sf_missing,,2,FALSE,,,,,FALSE,,FALSE,
Complete,Homework,,sf_complete,,1,TRUE,,,,,FALSE,,FALSE,
T1 - Unexcused tardiness for class or school,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Not In Class or With Group / Truancy,FALSE,Negative
T2 - Unauthorized presence in hallway during class time,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Not In Class or With Group / Truancy,FALSE,Negative
T2 - Leaving classroom or group without permission,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Not In Class or With Group / Truancy,FALSE,Negative
T2 - Unexcused absence from class,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Not In Class or With Group / Truancy,FALSE,Negative
T2 - Unexcused absence from school,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Not In Class or With Group / Truancy,FALSE,Negative
T2 - Unauthorized use of portable electronic devices during school hours,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T2 - Intentional misuse of school equipment/supplies/facilities,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T2 - Using computer/office equipment without permission,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Misusing Materials / Damaging Property;Inappropriate Contact / Unsafe Behavior,FALSE,Negative
T3 - Throwing objects that may cause injury or damage property,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
"T4 - Causing serious disruption/damage to school's computer system, electronic f",Behavior_Type,,,,99,FALSE,,,,4,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T4 - Intentional vandalism or destruction of property under $500,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T4 - Intentional vandalism or destruction of property over $500,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T3 - Engaging in behavior that demonstrates gang/neighborhood crew affiliation (,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Other,FALSE,Negative
T4 - Retaliation for reporting harassment and sexual harassment,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Other,FALSE,Negative
T1 - Any behavior not specifically enumerated in any other tier that is disrespe,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Other,FALSE,Negative
T2 - Any behavior not specifically enumerated in any other tier that causes disr,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Other,FALSE,Negative
T3 - Any behavior not specifically enumerated in any other tier that causes sign,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Other,FALSE,Negative
T4 - Any behavior not specifically enumerated in any other tier that causes disr,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Other,FALSE,Negative
T2 - Documented pattern of persistent Tier 1 behavior,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Other,FALSE,Negative
T3 - Documented pattern of persistent Tier 2 behavior,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Other,FALSE,Negative
T4 - Documented pattern of persistent Tier 3 behavior,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Other,FALSE,Negative
T5 - Documented pattern of persistent Tier 4 behavior,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Other,FALSE,Negative
T5 - Possession of a weapon,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Having / Using Potential or Real Weapon,TRUE,Negative
"T5 - Use, threatened use, or transfer of any weapon",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Having / Using Potential or Real Weapon,FALSE,Negative
T5 - Possession of fireworks or explosives,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Inappropriate Contact / Unsafe Behavior;Having / Using Potential or Real Weapon,FALSE,Negative
T5 - Using an article that is not normally considered a weapon to injure another,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Having / Using Potential or Real Weapon,FALSE,Negative
"T5 - Use, possession, or bringing to school a loaded or unloaded firearm",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Having / Using Potential or Real Weapon,FALSE,Negative
"T3 - Unauthorized possession, use, or distribution of over-the-counter medicatio",Behavior_Type,,,,99,FALSE,,,,3,FALSE,Drugs / Alcohol,FALSE,Negative
T5 - Possession of drug paraphernalia or controlled substance,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Drugs / Alcohol,FALSE,Negative
T5 - Possession or distribution of alcohol,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Drugs / Alcohol,FALSE,Negative
"T5 - Selling or distribution of marijuana, prescription drugs, controlled danger",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Drugs / Alcohol,FALSE,Negative
T3 - Gambling,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Other,FALSE,Negative
T5 - Commission or attempted commission of any act of sexual assault or sexual a,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Inappropriate Contact / Unsafe Behavior,FALSE,Negative
T2 - Lying with intent to mislead,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Lying / Cheating / Stealing,FALSE,Negative
T3 - Academic Dishonesty,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Lying / Cheating / Stealing,FALSE,Negative
T3 - Forgery,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Lying / Cheating / Stealing,FALSE,Negative
T4 - Tampering with or altering an official school record or document,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Lying / Cheating / Stealing,FALSE,Negative
T3 - Impulsive theft that does not involve going into personal belongings (takin,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Lying / Cheating / Stealing,FALSE,Negative
T4 - Planned theft that involves going into personal belonging or space,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Lying / Cheating / Stealing,FALSE,Negative
"T5 - Theft or attempted theft using force, coercion, intimidation, or threat of",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Lying / Cheating / Stealing,FALSE,Negative
"T1 - Excessive noise in the classroom, hall, or building",Behavior_Type,,,,99,FALSE,,,,1,FALSE,Disruptive / Disrespectful,FALSE,Negative
T1 - Behaviors that disrupt or interfere with classroom teaching and learning,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Disruptive / Disrespectful,FALSE,Negative
T4 - Interfering with school authorities or participating in a major disruption,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Disruptive / Disrespectful,FALSE,Negative
T1 - Communication or tone and language that is not respectful (including teasin,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Disruptive / Disrespectful,FALSE,Negative
T2 - Directing profanity or offensive gestures toward others,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Disruptive / Disrespectful,FALSE,Negative
"T3 - Posting or distributing material or lit that is disrespectful, demeaning, h",Behavior_Type,,,,99,FALSE,,,,3,FALSE,Disruptive / Disrespectful,FALSE,Negative
"T4 - Using obscene, seriously offensive, or abusive language or gestures",Behavior_Type,,,,99,FALSE,,,,4,FALSE,Disruptive / Disrespectful,FALSE,Negative
T4 - Sexual harassment,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Disruptive / Disrespectful,FALSE,Negative
T1 - Any (Tier 1) behavior or other conduct not specifically enumerated in any o,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Disruptive / Disrespectful,FALSE,Negative
"T3 - Verbal, written, or physical threat to person or property (including intimi",Behavior_Type,,,,99,FALSE,,,,3,FALSE,Bullying / Threatening / Planning Harm,FALSE,Negative
T3 - Hazing,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Bullying / Threatening / Planning Harm,FALSE,Negative
T5 - Using an article that is not normally considered a weapon to intimidate or,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Bullying / Threatening / Planning Harm;Fighting;Having / Using Potential or Real Weapon,FALSE,Negative
T5 - Planned assault/physical attack on student or staff where there is or has t,Behavior_Type,,,,99,FALSE,,,,5,FALSE,Bullying / Threatening / Planning Harm,FALSE,Negative
"T4 - Pushing, hitting, or fighting where there is no physical harm or weapon use",Behavior_Type,,,,99,FALSE,,,,4,FALSE,Fighting,FALSE,Negative
"T5 - Pushing, hitting, or fighting which results in a serious physical injury",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Fighting,FALSE,Negative
"T5 - Participating in group fight which has been planned, causes major disruptio",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Fighting,FALSE,Negative
T4 - Possession of tools or instruments which school administrators deem could b,Behavior_Type,,,,99,FALSE,,,,4,FALSE,Having / Using Potential or Real Weapon,FALSE,Negative
"T5 - Arson, Bio-hazard, Bomb threat",Behavior_Type,,,,99,FALSE,,,,5,FALSE,Misusing Materials / Damaging Property,FALSE,Negative
T1 - Inappropriate displays of affection,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Inappropriate Contact / Unsafe Behavior,FALSE,Negative
"T1 - Running in the classroom, hall, or building",Behavior_Type,,,,99,FALSE,,,,1,FALSE,Inappropriate Contact / Unsafe Behavior,FALSE,Negative
T2 - Inappropriate physical contact between students that may not be physically,Behavior_Type,,,,99,FALSE,,,,2,FALSE,Inappropriate Contact / Unsafe Behavior,FALSE,Negative
"T3 - Engaging in behavior that may cause harm to self or others (rough-housing,",Behavior_Type,,,,99,FALSE,,,,3,FALSE,Inappropriate Contact / Unsafe Behavior,FALSE,Negative
Neutral Incident #2,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Neutral #1,FALSE,Neutral
Neutral Incident #1,Behavior_Type,,,,99,FALSE,,,,3,FALSE,Neutral #1;Neutral #2,FALSE,Neutral
Positive Incident #1,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Positive #1,FALSE,Positive
Positive Incident #2,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Positive #1;Positive #2,FALSE,Positive
T1 - Noncompliance with an approved dress code,Behavior_Type,,,,99,FALSE,,,,-1,FALSE,Non-compliant / Not Prepared,FALSE,Negative
T1 - Attending class without required class materials or assigned work,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Non-compliant / Not Prepared,FALSE,Negative
T1 - Off-task behaviors that demonstrate disengagement from classroom learning,Behavior_Type,,,,99,FALSE,,,,1,FALSE,Non-compliant / Not Prepared,FALSE,Negative
"T1 - Refusal to comply w/ instr. / class / school rules w/o arguing, talking bac",Behavior_Type,,,,99,FALSE,,,,1,FALSE,Non-compliant / Not Prepared,FALSE,Negative
"T2 - Refusal to comply w/ instr. or rules & arguing, talking back, or walking aw",Behavior_Type,,,,99,FALSE,,,,2,FALSE,Non-compliant / Not Prepared;Disruptive / Disrespectful,FALSE,Negative
