*REQ* Section Name,*REQ* All Grades,Description,*REQ* Record Type ID
Lions,1,"Grade 1, Level 1",Schedule Group
Tigers,1,"Grade 1, Level 2",Schedule Group
Bears,1,"Grade 1, Level 3",Schedule Group
Stars,2,"Grade 2, Level 1",Schedule Group
Planets,1;2,"Grades 1 & 2, Level 2",Schedule Group
Meteors,2,"Grade 2, Level 3",Schedule Group
Snowflakes,3,"Grade 3, Level 1",Schedule Group
Rainbows,2;3,"Grades 2 & 3, Level 2",Schedule Group
Clouds,3,"Grade 3, Level 3",Schedule Group
