*REQ* Display Value,Category,Corresponding Value,*REQ* Type,*REQ* Record Type ID
Year,Reporting Period,,Time,Time
Semester,Reporting Period,2,Time,Time
Trimester,Reporting Period,3,Time,Time
Quarter,Reporting Period,4,Time,Time
Block,Reporting Period,,Time,Time
Period,Reporting Period,,Time,Time
Term,Reporting Period,1,Time,Time
Sixth,Reporting Period,6,Time,Time
Final,Reporting Period,,Time,Time
Fifth,Reporting Period,5,Time,Time
Seventh,Reporting Period,7,Time,Time
